name: Terraform CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7 # Replace with your Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' # Only apply on main branch
      run: terraform apply -auto-approve

    - name: Upload Terraform Plan (Pull Requests)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: plan.out
